# Generated by Django 4.1.6 on 2023-04-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(max_length=255, null=True, upload_to='files/'),
        ),
    ]
